<?php
# te vinden in de GET-parameters van bijvoorbeeld
# http://vblweb.wisseq.eu/Home/TeamDetail?teamGuid=BVBL1049G10%20%201

$teamGuid = 'BVBL1049HSE%20%201'; # orly A
# $teamGuid = 'BVBL1049HSE%20%202'; # orly B
# $teamGuid = 'BVBL1049G10%20%201'; # orly U10
# $teamGuid = 'BVBL1049G12%20%201'; # orly U12
# $teamGuid = 'BVBL1049G14%20%201'; # orly U14

$teamGuid = str_replace('%20', '+', $teamGuid);

# $matches initialiseren door vbl 'api' te vragen
#################################################

# Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "http://vblcb.wisseq.eu/VBLCB_WebService/data/TeamMatchesByGuid?teamGuid=" . $teamGuid);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");

$headers = array();
$headers[] = "Origin: http://vblweb.wisseq.eu";
$headers[] = "Accept-Encoding: gzip, deflate, sdch";
$headers[] = "Accept-Language: en-US,en;q=0.8,nl;q=0.6";
$headers[] = "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36";
$headers[] = "Accept: application/json, text/plain, */*";
$headers[] = "Referer: http://vblweb.wisseq.eu/Home/TeamDetail?teamGuid=BVBL1049HSE%20%201";
$headers[] = "Connection: keep-alive";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

$matches = json_decode($result);

# Omzetten naar ics
###################

# https://gist.github.com/jakebellacera/635416
# https://www.ietf.org/rfc/rfc5545.txt
header('Content-type: text/calendar; charset=utf-8');
header('Content-Disposition: attachment; filename=' . 'vbl-kalender.ics');

function dateToCal($timestamp) {
    return gmdate('Ymd\THis\Z', $timestamp);
}
function summary($match) {
    if ($match->uitslag === '') { 
        return $match->tTNaam . ' - ' . $match->tUNaam;
    } else { # $match->uitslag = '92- 85'
        return $match->tTNaam . ' ' . $match->uitslag . ' ' . $match->tUNaam;
    }
}
?>
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//hacksw/handcal//NONSGML v1.0//EN
CALSCALE:GREGORIAN
<?php
foreach ($matches as $i => $match) {
?>BEGIN:VEVENT
SUMMARY:<?php echo htmlspecialchars(summary($match)) ?> 
UID:<?php echo $match->guid ?> 
DESCRIPTION:<?php echo htmlspecialchars($match->pouleNaam) ?> 
LOCATION:<?php echo htmlspecialchars($match->accNaam) ?> 
DTSTART;TZID=Europe/Brussels:<?php echo dateToCal($match->jsDTCode / 1000) ?> 
DTEND;TZID=Europe/Brussels:<?php echo dateToCal(($match->jsDTCode / 1000) + 7200) ?> 
DTSTAMP:<?php echo dateToCal(time()) ?> 
URL;VALUE=URI:<?php echo htmlspecialchars('http://vblweb.wisseq.eu/Home/MatchDetail?wedguid=' . $match->guid) . "\n" ?>
END:VEVENT
<?php
}
?>
END:VCALENDAR
